import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { BriefcaseBusiness, CheckCircle2, CircleDollarSign, Clock3, FolderOpen, Images, RefreshCw, Sparkles, Star, ToggleLeft, ToggleRight, WalletCards } from "lucide-react";
import { Loader } from "../../components/common/UI";
import api from "../../services/api";
import { toast } from "../../components/common/UX";

export default function EditorDashboard() {
  const navigate = useNavigate(); const [metrics, setMetrics] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [availabilityBusy, setAvailabilityBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await api.get("/editors/me/dashboard"); setMetrics(response.data); } catch (err) { setError(err.response?.data?.message || "Unable to load the editor dashboard"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const toggleAvailability = async () => { if (!metrics || availabilityBusy) return; const next = !metrics.is_available; setAvailabilityBusy(true); setMetrics((current) => ({ ...current, is_available: next })); try { await api.put("/editors/me/profile", { is_available: next }); toast(next ? "You are now available for new projects" : "Availability paused", "success"); } catch (err) { setMetrics((current) => ({ ...current, is_available: !next })); toast(err.response?.data?.message || "Unable to update availability", "error"); } finally { setAvailabilityBusy(false); } };
  const cards = useMemo(() => metrics ? [
    ["New Requests", metrics.counts.new_requests, FolderOpen, "text-brand-goldLight", "/editor/updates"], ["Accepted Projects", metrics.counts.accepted_projects, CheckCircle2, "text-brand-gold", "/editor/updates"], ["Active Projects", metrics.counts.active_projects, BriefcaseBusiness, "text-amber-300", "/editor/updates"], ["Closed Projects", metrics.counts.completed_projects, Sparkles, "text-emerald-300", "/editor/updates"],
    ["Total Earnings", `Rs. ${Number(metrics.total_earnings).toLocaleString("en-LK")}`, CircleDollarSign, "text-emerald-300", "/editor/earnings"], ["Pending Earnings", `Rs. ${Number(metrics.pending_earnings).toLocaleString("en-LK")}`, Clock3, "text-amber-300", "/editor/earnings"], ["Rating", `${Number(metrics.rating).toFixed(1)} / 5`, Star, "text-brand-rating", "/editor/profile", `${metrics.rating_count} reviews`], ["Profile Completion", `${metrics.profile_completion}%`, Sparkles, "text-brand-goldLight", "/editor/profile"],
  ] : [], [metrics]);
  const maxEarning = Math.max(...(metrics?.monthly_earnings || []).map((item) => item.amount), 1);
  return <section className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><header className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-gold">Editor workspace</p><h1 className="mt-1 text-3xl font-bold">Dashboard</h1><p className="mt-2 text-sm text-slate-400">Manage requests, projects, earnings, and your public profile.</p></div><button type="button" onClick={toggleAvailability} disabled={!metrics || availabilityBusy} className={`flex items-center gap-3 rounded-xl border px-4 py-3 text-left ${metrics?.is_available ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-200" : "border-white/10 bg-white/5 text-gray-400"}`}>{metrics?.is_available ? <ToggleRight size={28} /> : <ToggleLeft size={28} />}<span><span className="block text-sm font-semibold">{metrics?.is_available ? "Available for work" : "Not available"}</span><span className="block text-[11px] opacity-65">Persisted on your public profile</span></span></button></header>
    {loading ? <Loader label="Loading your workspace…" /> : error ? <div className="glass rounded-2xl p-10 text-center"><p className="text-red-400">{error}</p><button onClick={load} className="mt-4 inline-flex items-center gap-2 text-brand-gold"><RefreshCw size={16} /> Try again</button></div> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, tone, route, note]) => <button type="button" key={label} onClick={() => navigate(route)} className="glass motion-panel rounded-2xl p-5 text-left"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.1em] text-gray-500">{label}</p><p className="mt-3 text-2xl font-bold text-white">{value}</p>{note && <p className="mt-1 text-xs text-gray-500">{note}</p>}</div><span className={`rounded-xl bg-white/5 p-2.5 ${tone}`}><Icon size={20} /></span></div>{label === "Profile Completion" && <div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-brand-gradient" style={{ width: `${metrics.profile_completion}%` }} /></div>}</button>)}</div>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="glass rounded-2xl p-5 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="font-semibold">Monthly Earnings</p><p className="text-xs text-gray-500">Released/captured project earnings from backend records</p></div><WalletCards className="text-brand-gold" size={21} /></div><div className="flex h-44 items-end gap-3">{metrics.monthly_earnings.map((item) => <div key={item.month} className="flex h-full flex-1 flex-col justify-end gap-2"><div title={`Rs. ${item.amount}`} className="min-h-1 rounded-t-lg bg-gradient-to-t from-brand-goldDeep to-brand-goldLight" style={{ height: `${Math.max(item.amount ? 8 : 2, item.amount / maxEarning * 100)}%` }} /><span className="text-center text-[10px] text-gray-500">{item.month.slice(5)}</span></div>)}</div></section><section className="glass rounded-2xl p-5 sm:p-6"><p className="font-semibold">Portfolio & Profile</p><p className="mt-1 text-xs text-gray-500">Keep your real public profile complete.</p><div className="mt-5 rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="flex items-center justify-between"><span className="text-sm text-gray-400">Portfolio projects</span><span className="text-xl font-bold">{metrics.portfolio_count}</span></div></div><button onClick={() => navigate("/editor/profile")} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-brand-gradient px-4 py-3 text-sm font-semibold"><Images size={17} /> Manage Portfolio</button></section></div></>}
  </section>;
}
