import { useEffect, useState } from "react";
import { WalletCards } from "lucide-react";
import { Badge, Loader } from "../../components/common/UI";
import api from "../../services/api";

const money = (value) => `LKR ${Number(value || 0).toLocaleString("en-LK", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export default function EditorEarningsPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { setData(null); setError(""); api.get("/editors/me/commission-statements", { params: { month } }).then((r) => setData(r.data)).catch((e) => setError(e.response?.data?.detail || "Unable to load earnings")); }, [month]);
  return <section className="mx-auto max-w-6xl px-5 py-8"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-brand-gold">10% earnings-based commission</p><h1 className="mt-1 flex items-center gap-3 text-2xl font-bold"><WalletCards className="text-brand-gold" /> Earnings & Commission</h1><p className="mt-2 text-sm text-slate-400">EditZone retains 10% of each verified project amount. Client service fees are never included in your earnings.</p></div><label className="text-sm text-slate-400">Month<input aria-label="Earnings month" type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="ml-3 rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-white" /></label></header>
    {!data && !error ? <Loader /> : error ? <p className="text-red-400">{error}</p> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Gross project earnings", data.gross_earnings], ["EditZone commission · 10%", data.commission], ["Net payout amount", data.net_payout], ["Paid projects", data.paid_projects]].map(([label, value]) => <article key={label} className="glass rounded-xl p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{label === "Paid projects" ? value : money(value)}</p></article>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-3">{[["Pending payout", data.pending_payout], ["Paid payout", data.paid_payout], ["Reversed / refunded", data.reversed_earnings]].map(([label, value]) => <article key={label} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{money(value)}</p></article>)}</div>
      <h2 className="mb-3 mt-8 font-bold">Commission statements</h2><div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[650px] text-sm"><thead className="bg-white/[.04] text-left text-slate-400"><tr><th className="p-4">Order</th><th>Gross</th><th>Commission</th><th>Net</th><th>Payout status</th></tr></thead><tbody>{(data.payouts || []).map((row) => <tr key={row.id} className="border-t border-white/10"><td className="p-4">{row.order_id}</td><td>{money((row.gross_amount_minor || 0) / 100)}</td><td>{money((row.editor_commission_minor || 0) / 100)}</td><td>{money(((row.net_amount_minor || 0) + (row.adjustments_minor || 0)) / 100)}</td><td><Badge tone={row.payout_status === "PAID" ? "success" : "warning"}>{row.payout_status}</Badge></td></tr>)}</tbody></table>{!data.payouts?.length && <p className="p-8 text-center text-slate-500">No payout-eligible projects in this month.</p>}</div>
      <h2 className="mb-3 mt-8 font-bold">Payout history</h2><div className="space-y-3">{(data.payouts || []).map((p) => <article key={p.id} className="glass flex flex-wrap items-center justify-between gap-3 rounded-xl p-4"><div><p className="font-semibold">{p.month} · {money((p.net_amount_minor + (p.adjustments_minor || 0)) / 100)}</p><p className="text-xs text-slate-500">Manual bank payout · Recorded by admin{p.payout_reference ? ` · ${p.payout_reference}` : ""}</p></div><Badge tone={p.payout_status === "PAID" ? "success" : "warning"}>{p.payout_status}</Badge></article>)}</div></>}
  </section>;
}
