import { useEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronRight, Eye, Heart, LoaderCircle, Trash2, Volume2, VolumeX, X } from "lucide-react";
import { protectedMediaUrl, resolveMediaUrl } from "../../services/media";
import { statusApi } from "../../services/statuses";
import { ConfirmModal, toast } from "../common/UX";

const age = (value) => { const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes}m` : `${Math.floor(minutes / 60)}h`; };

export default function StatusViewer({ group, initialIndex, onClose, onChange, onDeleted }) {
  const firstUnseen = group?.statuses.findIndex((item) => !item.is_viewed_by_me) ?? -1;
  const [index, setIndex] = useState(Number.isInteger(initialIndex) ? initialIndex : firstUnseen >= 0 ? firstUnseen : 0);
  const [url, setUrl] = useState(""); const [loading, setLoading] = useState(false); const [mediaError, setMediaError] = useState("");
  const [muted, setMuted] = useState(true); const [busy, setBusy] = useState(false); const [people, setPeople] = useState(null); const [confirm, setConfirm] = useState(false);
  const [heartPop, setHeartPop] = useState(false);
  const videoRef = useRef(null); const panelRef = useRef(null); const onChangeRef = useRef(onChange); const status = group?.statuses[index]; const groupEditorId = group?.editor.id; const groupStatusCount = group?.statuses.length || 0;
  useEffect(() => { onChangeRef.current = onChange; }, [onChange]);
  // Recalculate only when opening another editor or an explicit dashboard
  // story. View/like state updates must not jump to another story.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (!group) return; const unseen = group.statuses.findIndex((item) => !item.is_viewed_by_me); setIndex(Number.isInteger(initialIndex) ? Math.min(initialIndex, group.statuses.length - 1) : unseen >= 0 ? unseen : 0); }, [groupEditorId, initialIndex]);
  // Opening another story is the lifecycle boundary; count/state changes must
  // not restart media playback or submit a second view request.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (!status) return; let live = true; const currentVideo = videoRef.current; setUrl(""); setMediaError(""); setLoading(true); protectedMediaUrl(status.media_url).then((value) => live && setUrl(value)).catch(() => live && setMediaError("Status media could not be loaded.")).finally(() => live && setLoading(false)); statusApi.view(status.id).then(({ data }) => onChangeRef.current?.({ ...status, ...data })).catch(() => undefined); return () => { live = false; currentVideo?.pause(); }; }, [status?.id, status?.media_url]);
  useEffect(() => { if (!groupEditorId) return undefined; const previousFocus = document.activeElement; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; panelRef.current?.focus(); const key = (event) => { if (event.key === "Escape") onClose(); if (event.key === "ArrowRight") setIndex((i) => Math.min(groupStatusCount - 1, i + 1)); if (event.key === "ArrowLeft") setIndex((i) => Math.max(0, i - 1)); if (event.key === "Tab" && !confirm) { const focusable = [...(panelRef.current?.querySelectorAll('button:not([disabled]), [href], input:not([disabled]), [tabindex]:not([tabindex="-1"])') || [])]; if (!focusable.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; window.addEventListener("keydown", key); return () => { window.removeEventListener("keydown", key); document.body.style.overflow = previousOverflow; previousFocus?.focus?.(); }; }, [groupEditorId, groupStatusCount, confirm, onClose]);
  if (!group || !status) return null;
  const changeLike = async () => { if (busy || status.is_owner) return; setBusy(true); const optimistic = { ...status, is_liked_by_me: !status.is_liked_by_me, liked_by_me: !status.is_liked_by_me, like_count: Math.max(0, status.like_count + (status.is_liked_by_me ? -1 : 1)) }; if (optimistic.is_liked_by_me) { setHeartPop(true); window.setTimeout(() => setHeartPop(false), 500); } onChange?.(optimistic); try { const { data } = await (status.is_liked_by_me ? statusApi.unlike(status.id) : statusApi.like(status.id)); onChange?.({ ...optimistic, ...data }); } catch (error) { onChange?.(status); toast(error.response?.data?.detail || error.response?.data?.message || "Unable to update like", "error"); } finally { setBusy(false); } };
  const showPeople = async (type) => { setPeople({ type, loading: true, users: [] }); try { const { data } = await statusApi.people(status.id, type); setPeople({ type, loading: false, users: data.users }); } catch (error) { toast(error.response?.data?.message || "Unable to load insights", "error"); setPeople(null); } };
  const remove = async () => { setBusy(true); try { await statusApi.remove(status.id); setConfirm(false); onDeleted?.(status.id); onClose(); toast("Status deleted successfully.", "success"); } catch (error) { toast(error.response?.data?.detail || error.response?.data?.message || "Unable to delete status", "error"); } finally { setBusy(false); } };
  return <div role="dialog" aria-modal="true" aria-label={`${group.editor.name}'s status`} className="fixed inset-0 z-[80] flex items-center justify-center bg-black/85 px-2 pb-[max(1rem,env(safe-area-inset-bottom))] pt-[max(4.5rem,env(safe-area-inset-top))] backdrop-blur-sm sm:px-4 sm:pb-5 sm:pt-20" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div ref={panelRef} tabIndex={-1} className="relative flex h-[calc(100dvh-5.5rem)] max-h-[calc(100dvh-100px)] w-full max-w-[430px] flex-col overflow-hidden rounded-3xl border border-[#B49D50]/45 bg-[#0b0b0d] shadow-[0_30px_90px_rgba(0,0,0,.75)] outline-none motion-panel">
    <div className="absolute inset-x-0 top-0 z-20 bg-gradient-to-b from-black/80 to-transparent p-3"><div className="flex gap-1">{group.statuses.map((_, i) => <span key={i} className="h-1 flex-1 overflow-hidden rounded bg-white/25"><span className={`block h-full bg-white ${i <= index ? "w-full" : "w-0"}`} /></span>)}</div><div className="mt-3 flex items-center gap-3"><img src={resolveMediaUrl(group.editor.profile_image)} alt="" className="h-9 w-9 rounded-full bg-white/10 object-cover" /><div className="flex-1"><p className="text-sm font-semibold">{group.editor.name}</p><p className="text-xs text-white/60">{age(status.created_at)}</p></div>{status.media_type === "video" && <button onClick={() => setMuted((v) => !v)} aria-label={muted ? "Unmute" : "Mute"} className="p-2">{muted ? <VolumeX size={19} /> : <Volume2 size={19} />}</button>}{status.can_delete && <button onClick={() => setConfirm(true)} aria-label="Delete status" className="p-2 text-red-300"><Trash2 size={18} /></button>}<button onClick={onClose} aria-label="Close status viewer" className="p-2"><X size={22} /></button></div></div>
    <div className="relative flex min-h-0 flex-1 items-center justify-center bg-black p-1">{loading && <LoaderCircle className="animate-spin text-brand-gold" />}{mediaError && <p className="px-8 text-center text-sm text-red-300">{mediaError}</p>}{url && status.media_type === "video" && <video ref={videoRef} src={url} autoPlay playsInline muted={muted} preload="metadata" onError={() => setMediaError("Video failed to play.")} className="h-auto max-h-full w-auto max-w-full object-contain" />}{url && status.media_type === "image" && <img src={url} alt={status.caption || `${group.editor.name}'s status`} onError={() => setMediaError("Image failed to load.")} className="h-auto max-h-full w-auto max-w-full object-contain" />}<button disabled={index === 0} onClick={() => setIndex((i) => i - 1)} aria-label="Previous status" className="absolute left-0 top-20 bottom-20 w-1/3 disabled:pointer-events-none"><ChevronLeft className="ml-2 opacity-60" /></button><button disabled={index === group.statuses.length - 1} onClick={() => setIndex((i) => i + 1)} aria-label="Next status" className="absolute right-0 top-20 bottom-20 flex w-1/3 justify-end disabled:pointer-events-none"><ChevronRight className="mr-2 opacity-60" /></button></div>
    <div className="z-10 border-t border-white/10 bg-[#111114] px-4 pb-[max(1rem,env(safe-area-inset-bottom))] pt-3">{status.caption && <p className="mb-3 break-words text-sm text-gray-200">{status.caption}</p>}<div className="flex items-center gap-3">{status.is_owner ? <><button onClick={() => showPeople("likes")} className="flex items-center gap-1.5 text-sm text-gray-300"><Heart size={17} /> {status.like_count} Likes</button><button onClick={() => showPeople("views")} className="flex items-center gap-1.5 text-sm text-gray-300"><Eye size={17} /> {status.view_count} Views</button></> : <button disabled={busy} onClick={changeLike} aria-label={status.is_liked_by_me ? "Unlike status" : "Like status"} className={`relative flex items-center gap-2 rounded-full border px-4 py-2 text-sm transition-transform ${heartPop ? "scale-110" : "scale-100"} ${status.is_liked_by_me ? "border-rose-400/40 bg-rose-400/10 text-rose-300" : "border-white/15"}`}>{heartPop && <Heart aria-hidden="true" size={18} fill="currentColor" className="pointer-events-none absolute -top-6 left-5 animate-ping text-rose-400" />}<Heart size={19} fill={status.is_liked_by_me ? "currentColor" : "none"} /> {status.like_count} Likes</button>} {!status.is_owner && <span className="flex items-center gap-1.5 text-sm text-gray-400"><Eye size={17} /> {status.view_count} Views</span>}</div></div>
    {people && <div className="absolute inset-x-0 bottom-0 z-30 max-h-[60%] overflow-y-auto rounded-t-3xl border-t border-white/10 bg-[#18181c] p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">{people.type === "views" ? "Viewed by" : "Liked by"}</h3><button onClick={() => setPeople(null)} aria-label="Close insights"><X /></button></div>{people.loading ? <LoaderCircle className="mx-auto my-8 animate-spin" /> : people.users.length ? <div className="mt-4 space-y-3">{people.users.map((person) => <div key={person.id} className="flex items-center gap-3">{person.profile_image ? <img src={resolveMediaUrl(person.profile_image)} alt="" className="h-10 w-10 rounded-full object-cover" /> : <span className="grid h-10 w-10 place-items-center rounded-full bg-avatar-gradient text-xs font-bold">{person.name.slice(0, 2).toUpperCase()}</span>}<span className="text-sm">{person.name}</span></div>)}</div> : <p className="py-8 text-center text-sm text-gray-500">No one yet</p>}</div>}
  </div><ConfirmModal open={confirm} title="Delete this status?" description="This status and its likes will be permanently removed." confirmLabel="Delete" danger busy={busy} onCancel={() => setConfirm(false)} onConfirm={remove} /></div>;
}
